# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-11 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='link',
        ),
        migrations.AddField(
            model_name='service',
            name='details',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
