# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-11 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210211_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tel',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
