# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-11 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20210211_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='more_info',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
